/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
//import inventorymanager.main;
/**
 *
 * @author Nikhil
 */
public class login extends javax.swing.JFrame {

    
    public login() {
        initComponents();
        //setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginMsgFeild = new javax.swing.JLabel();
        passwordFeild = new javax.swing.JPasswordField();
        signupButton = new javax.swing.JButton();
        usernameFeild = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        forgotPassButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Manger - LOGIN ");
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 685));
        getContentPane().setLayout(new java.awt.CardLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1280, 685));

        loginMsgFeild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginMsgFeild.setForeground(new java.awt.Color(255, 0, 0));
        loginMsgFeild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginMsgFeild.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginMsgFeild.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(loginMsgFeild);
        loginMsgFeild.setBounds(760, 200, 470, 30);

        passwordFeild.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordFeild.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.add(passwordFeild);
        passwordFeild.setBounds(890, 310, 320, 30);

        signupButton.setBorderPainted(false);
        signupButton.setContentAreaFilled(false);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(signupButton);
        signupButton.setBounds(980, 510, 70, 20);

        usernameFeild.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameFeild.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFeildActionPerformed(evt);
            }
        });
        jLayeredPane1.add(usernameFeild);
        usernameFeild.setBounds(890, 250, 320, 30);

        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(loginButton);
        loginButton.setBounds(890, 430, 180, 40);

        checkBox.setBorder(null);
        checkBox.setContentAreaFilled(false);
        jLayeredPane1.add(checkBox);
        checkBox.setBounds(780, 360, 360, 40);

        forgotPassButton.setBorderPainted(false);
        forgotPassButton.setContentAreaFilled(false);
        forgotPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(forgotPassButton);
        forgotPassButton.setBounds(400, 280, 130, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1.png"))); // NOI18N
        jLayeredPane1.add(Background);
        Background.setBounds(0, 0, 1280, 685);

        getContentPane().add(jLayeredPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassButtonActionPerformed

    private void usernameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFeildActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        register register= new register();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String loginMsg = "Wrong Username or Password Entered !";
        String a=usernameFeild.getText();
        String b=passwordFeild.getText();
        if(checkBox.isSelected()){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanager","root","nikhil");  
                Statement st = con.createStatement();
                ResultSet rs;
                rs = st.executeQuery("select * from logincredentials");
                while(rs.next()){
                    String username=rs.getString("username");
                    String password=rs.getString("password");
                    String company=rs.getString("company");
                    String name=rs.getString("name");

                    if(a.equals(username) && password.equals(b)){
                        main info=new main(name,username,company);
                        info.setVisible(true);
                        this.setVisible(false);
                        break;
                    }else{ 
                        loginMsgFeild.setText(loginMsg);
                    }  
                }
                con.close();
            }catch(SQLException se){
                //Handle errors for JDBC
                se.printStackTrace();
            }catch(Exception e){
                //Handle errors for Class.forName
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Error while establishing Connection");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please accept terms and conditions");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton forgotPassButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginMsgFeild;
    private javax.swing.JPasswordField passwordFeild;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameFeild;
    // End of variables declaration//GEN-END:variables
}
