/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.System.exit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikhil
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public register() {
        initComponents();
        //setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Register = new javax.swing.JButton();
        check = new javax.swing.JCheckBox();
        Reg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        licensekey = new javax.swing.JTextField();
        repassword = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration - Inventory Manager");
        setResizable(false);

        jPanel1.setLayout(null);

        Register.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        Register.setText("Register");
        Register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register);
        Register.setBounds(230, 580, 180, 50);
        jPanel1.add(check);
        check.setBounds(80, 520, 90, 40);

        Reg.setBorderPainted(false);
        Reg.setContentAreaFilled(false);
        Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegActionPerformed(evt);
            }
        });
        jPanel1.add(Reg);
        Reg.setBounds(1010, 350, 130, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Go to Login");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 590, 110, 40);

        licensekey.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(licensekey);
        licensekey.setBounds(230, 420, 310, 40);

        repassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(repassword);
        repassword.setBounds(230, 370, 310, 40);

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(password);
        password.setBounds(230, 320, 310, 40);

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(username);
        username.setBounds(230, 270, 310, 40);

        company.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(company);
        company.setBounds(230, 470, 310, 40);

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(name);
        name.setBounds(230, 220, 310, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/3.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1280, 680);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Register New User");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        String a = name.getText();
        String b = username.getText();
        String c = password.getText();
        String d = company.getText();
        String f = licensekey.getText();
        String ed = repassword.getText();
        if(check.isSelected()){
            if(c.equals(ed)){
                try{
                    Class.forName("java.sql.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanager","root","nikhil");
                    Statement stmt = con.createStatement();
                    int s = stmt.executeUpdate("insert into logincredentials (name,username,password,licensekey,company) values ('"+a+"','"+b+"','"+c+"','"+f+"','"+d+"');");
                    JOptionPane.showMessageDialog(null, "Congratulations, You are Registered.");
                    this.setVisible(false);
                    login info=new login();
                    info.setVisible(true);
                }catch(SQLException se){
                    //Handle errors for JDBC
                    se.printStackTrace();
                }catch(Exception e){
                    //Handle errors for Class.forName
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null,"ERROR! Registration Failed");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Entered passwords dosent match.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Accept the terms and conditions");
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String a = name.getText();
        String b = username.getText();
        String c = password.getText();
        String d = company.getText();
        String f = licensekey.getText();
        String ed = repassword.getText();
        if(check.isSelected()){
            if(c.equals(ed)){
                try{
                    Class.forName("java.sql.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanager","root","nikhil");
                    Statement stmt = con.createStatement();
                    int s = stmt.executeUpdate("insert into logincredentials (name,username,password,licensekey,company) values ('"+a+"','"+b+"','"+c+"','"+f+"','"+d+"');");
                    JOptionPane.showMessageDialog(null, "Congratulations, You are Registered.");
                    this.setVisible(false);
                    login info=new login();
                    info.setVisible(true);
                }catch(SQLException se){
                    //Handle errors for JDBC
                    se.printStackTrace();
                }catch(Exception e){
                    //Handle errors for Class.forName
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null,"ERROR! Registration Failed");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Entered passwords dosent match.");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Accept the terms and conditions");
        }
    }//GEN-LAST:event_RegActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login info=new login();
        info.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        about info = new about();
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to Log Out", "LOG OUT", dialogButton);
        if(dialogResult == 0) {
          exit(0);
        } else {
          System.out.println("No Option");
        } 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        login info=new login();
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        register info = new register();
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reg;
    private javax.swing.JButton Register;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField company;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField licensekey;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField repassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
