/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Nikhil
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    String la;
    String lb;
    String lc,u,p,c,l,n;
    public user() {
        user info = new user(la,lb,lc);
        info.setVisible(true);
    }
    public user(String a,String b,String c){
        la=a;
        lb=b;
        lc=c;
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        newname.setVisible(false);
        newusername.setVisible(false);
        newpassword.setVisible(false);
        newcompany.setVisible(false);
        newlicensekey.setVisible(false);
        discard.setVisible(false);
        save.setVisible(false);
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loaddata(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanager","root","nikhil");  
            Statement st=con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select * from logincredentials where name ='"+la+"' and username ='"+lb+"'");
            while(rs.next()){
                int x = rs.getInt("id");
                u=rs.getString("username");
                p=rs.getString("password");
                c=rs.getString("company");
                l=rs.getString("licensekey");
                n=rs.getString("name");
                id.setText(String.valueOf(x));
                name.setText(n);
                username.setText(u);
                password.setText(p);
                company.setText(c);
                licensekey.setText(l);
            }
            con.close();
        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error while establishing Connection");
        }
    }
    
    private void discard(){
        loaddata();
        name.setVisible(true);
        username.setVisible(true);
        password.setVisible(true);
        company.setVisible(true);
        licensekey.setVisible(true);
        updatebutton.setVisible(true);
        
        newname.setVisible(false);
        newusername.setVisible(false);
        newpassword.setVisible(false);
        newcompany.setVisible(false);
        newlicensekey.setVisible(false);
        discard.setVisible(false);
        save.setVisible(false);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        company = new javax.swing.JLabel();
        licensekey = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        password = new javax.swing.JLabel();
        updatebutton = new javax.swing.JButton();
        newpassword = new javax.swing.JTextField();
        newcompany = new javax.swing.JTextField();
        newlicensekey = new javax.swing.JTextField();
        newname = new javax.swing.JTextField();
        newusername = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        discard = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 685));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 280, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("License Key :-");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 490, 170, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :-");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 350, 220, 30);

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name);
        name.setBounds(450, 200, 400, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name :-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 210, 110, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(350, 320, 500, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(350, 390, 500, 20);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(350, 530, 500, 20);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(350, 250, 500, 20);

        company.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        company.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(company);
        company.setBounds(560, 410, 290, 40);

        licensekey.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        licensekey.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(licensekey);
        licensekey.setBounds(510, 480, 340, 40);

        username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(username);
        username.setBounds(490, 270, 360, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company Name :-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 420, 220, 30);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(350, 460, 500, 20);

        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(password);
        password.setBounds(490, 350, 290, 30);

        updatebutton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatebutton.setText("Update Profile");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton);
        updatebutton.setBounds(490, 570, 210, 60);

        newpassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(newpassword);
        newpassword.setBounds(480, 340, 370, 40);

        newcompany.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(newcompany);
        newcompany.setBounds(560, 410, 290, 40);

        newlicensekey.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(newlicensekey);
        newlicensekey.setBounds(510, 480, 340, 40);

        newname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(newname);
        newname.setBounds(450, 200, 400, 40);

        newusername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(newusername);
        newusername.setBounds(490, 270, 360, 40);

        save.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(640, 570, 210, 60);

        discard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discard.setText("Discard");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });
        jPanel1.add(discard);
        discard.setBounds(350, 570, 210, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Unique Account ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 50, 210, 30);

        id.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(id);
        id.setBounds(70, 80, 200, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/9.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1280, 680);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Save Data");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Register New User");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigate");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Home");
        jMenuItem6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Manage Vendor");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Manage Product");
        jMenuItem3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Manage Employee");
        jMenuItem4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tools");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Manage User Account");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        login info=new login();
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to Log Out", "LOG OUT", dialogButton);
        if(dialogResult == 0) {
            exit(0);
        } else {
            System.out.println("No Option");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        save info=new save(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        main info=new main(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        main info=new main(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        vendorManager info=new vendorManager(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        manageProduct info=new manageProduct(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        manageEmployee info=new manageEmployee(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        main info=new main(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        about info = new about(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        name.setVisible(false);
        username.setVisible(false);
        password.setVisible(false);
        company.setVisible(false);
        licensekey.setVisible(false);
        updatebutton.setVisible(false);
        
        newname.setVisible(true);
        newusername.setVisible(true);
        newpassword.setVisible(true);
        newcompany.setVisible(true);
        newlicensekey.setVisible(true);
        discard.setVisible(true);
        save.setVisible(true);
        
        newname.setText(n);
        newusername.setText(u);
        newpassword.setText(p);
        newcompany.setText(c);
        newlicensekey.setText(l);
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:


        String a = newname.getText();
        String b = newusername.getText();
        String c = newpassword.getText();
        String d = newcompany.getText();
        String f = newlicensekey.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanager","root","nikhil");  
            Statement st=con.createStatement();
            ResultSet rs;
            st.executeUpdate("update logincredentials set name='"+a+"', username='"+b+"', password='"+c+"', company='"+d+"', licensekey='"+f+"' where name ='"+la+"' and username ='"+lb+"';");
            JOptionPane.showMessageDialog(null,"User data updated successfully");
            loaddata();
            con.close();
            discard();
        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error while establishing Connection");
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        // TODO add your handling code here:
        discard();
    }//GEN-LAST:event_discardActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        user info = new user(la,lb,lc);
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        register info = new register();
        info.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel company;
    private javax.swing.JButton discard;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel licensekey;
    private javax.swing.JLabel name;
    private javax.swing.JTextField newcompany;
    private javax.swing.JTextField newlicensekey;
    private javax.swing.JTextField newname;
    private javax.swing.JTextField newpassword;
    private javax.swing.JTextField newusername;
    private javax.swing.JLabel password;
    private javax.swing.JButton save;
    private javax.swing.JButton updatebutton;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
